<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Patient Statistics Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .report-title { font-size: 18px; font-weight: bold; }
        .report-subtitle { font-size: 14px; color: #555; }
        .report-meta { font-size: 12px; margin-bottom: 20px; }
        .chart-container { width: 100%; height: 500px; margin-top: 30px; }
        .footer { font-size: 10px; text-align: center; margin-top: 30px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <div class="report-title">Statistik Pesakit X-ray</div>
        <div class="report-subtitle">Patient distribution by gender across different sub-departments</div>
        <div class="report-meta">
            <?= $bahagian_utama ?> | <?= $kategori ?>
            <?php if (!empty($month) || !empty($year)): ?>
                | Period: 
                <?= !empty($month) ? date('F', mktime(0, 0, 0, $month, 1)) : '' ?>
                <?= !empty($year) ? $year : '' ?>
            <?php endif; ?>
            | Generated on: <?= date('d/m/Y H:i') ?>
        </div>
    </div>

    <div class="chart-container">
        <!-- This will be replaced with an image of your chart -->
        <img src="<?= base_url('path_to_your_chart_image') ?>" style="width: 100%; height: auto;">
    </div>

    <div class="footer">
        Report generated by X-ray Department &copy; <?= date('Y') ?>
    </div>
</body>
</html>